version: '3'

services:
  app:
    build: docker/app/
    volumes:
      - ./:/srv/app/
    env_file:
      - ./docker/.docker.env
    ports:
      - "80:80"
    working_dir: /srv/app/

  database:
    image: mariadb:10.3
    env_file:
      - ./docker/.docker.env
    ports:
      - "3307:3306"

